[flake8]
max-line-length = 100

# Details of ignores:
# E121: continuation line under-indented for hanging indent (not strictly PEP8)
# E123: closing bracket does not match indentation of opening bracket’s line (not strictly PEP8)
# E126: continuation line over-indented for hanging indent (not strictly PEP8)
# E203: whitespace before ':' (added deliberately by black)
# E704: multiple statements on one line (def) (not strictly PEP8)
# W503: line break before binary operator (not strictly PEP8)
ignore = "E121,E123,E126,E203,E704,W292,W503"

[tool.black]
line-length = 100
